version: 1.0.{build}

image: Visual Studio 2015

environment:
  matrix:
    - platform: win32
      ARCH: win32-msvc9
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 9 2008"
      MSVCVERSION: "v90"
      MSVCYEAR: "vs2008"
      MSVCABR: "9"
      VC_VER: 9.0
      PYTHONPATH: c:\Python27\
      WITH_SODIUM: OFF
    - platform: x64
      ARCH: x64-msvc9
      configuration: Release
      CMAKE_GENERATOR: Visual Studio 9 2008 Win64
      MSVCVERSION: v90
      MSVCYEAR: vs2008
      MSVCABR: 9
      VC_VER: 9.0
      PYTHONPATH: c:\Python27-x64\
      WITH_SODIUM: OFF
    - platform: win32
      ARCH: win32-msvc10
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 10 2010"
      MSVCVERSION: "v100"
      MSVCYEAR: "vs2010"
      MSVCABR: "10"
      VC_VER: 10.0
      PYTHONPATH: c:\Python33\
      WITH_SODIUM: OFF
    - platform: x64
      ARCH: x64-msvc10
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
      MSVCVERSION: "v100"
      MSVCYEAR: "vs2010"
      MSVCABR: "10"
      VC_VER: 10.0
      PYTHONPATH: c:\Python33-x64\
      WITH_SODIUM: OFF
    - platform: win32
      ARCH: win32-msvc12
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 12 2013"
      MSVCVERSION: "v120"
      MSVCYEAR: "vs2013"
      MSVCABR: "12"
      VC_VER: 13.0
      PYTHONPATH: c:\Python33\
      WITH_SODIUM: OFF
    - platform: x64
      ARCH: x64-msvc12
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
      MSVCVERSION: "v120"
      MSVCYEAR: "vs2013"
      MSVCABR: "12"
      VC_VER: 13.0
      PYTHONPATH: c:\Python33-x64\
      WITH_SODIUM: OFF
    - platform: win32
      ARCH: win32-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015"
      MSVCVERSION: "v140"
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python35\
      WITH_SODIUM: OFF
    - platform: x64
      ARCH: x64-msvc14
      configuration: Release
      CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
      MSVCVERSION: "v140"
      MSVCYEAR: "vs2015"
      MSVCABR: "14"
      VC_VER: 14.0
      PYTHONPATH: c:\Python35-x64\
      WITH_SODIUM: OFF
init:
  # go to hell Xamarin (see http://help.appveyor.com/discussions/problems/4569)
  - del "C:\Program Files (x86)\MSBuild\4.0\Microsoft.Common.Targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - del "C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  #RDP from start
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 #mysql client
  - cmd: cd C:\projects\
  - cmd: md mysql-connector-c-1.1.9-src
  - appveyor DownloadFile "https://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-1.1.9.zip"
  - cmd: 7z -y x mysql-connector-c++-1.1.9.zip -oC:\projects\mysql-connector-c-1.1.9-src
  - cmd: cd "C:\projects\mysql-connectors-ci"
  
install:
  #- cmd: if %ARCH%==x64-msvc9 xcopy C:\projects\zmq-windows-ci\patch "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include"
  #- cmd: if %ARCH%==win32-msvc9 xcopy C:\projects\zmq-windows-ci\patch "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include"
  - cmd: if %ARCH%==win32-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc9 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==x64-msvc9 call "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat"
  - cmd: if %ARCH%==win32-msvc9 set path=C:\Windows\Microsoft.NET\Framework\v4.0.30319;%path%
  - cmd: if %ARCH%==win32-msvc10 call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==x64-msvc10 call call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x64
  - cmd: if %ARCH%==x64-msvc10 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - cmd: if %ARCH%==win32-msvc12 call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==win32-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - cmd: if %ARCH%==x64-msvc12 call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
  - cmd: if %ARCH%==x64-msvc14 call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: set PYTHONPATH=%PYTHONPATH%
  - cmd: set BOOST_ROOT=C:\Libraries\boost_1_63_0
  - cmd: cd C:\projects\mysql-connector-c-1.1.9-src\mysql-connector-c++-1.1.9\win
  - cmake .. -G "%CMAKE_GENERATOR%" -DCMAKE_CXX_FLAGS_RELEASE="/MT /O2 /D NDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="/D_DEBUG /MTd /Od /Zi" -DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\mysql-connector-c-6.1.6-src\Release

build_script:
  - cmd: if %ARCH%==x64-msvc10 call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 Release
  - cmd: cd C:\projects\mysql-connector-c-1.1.9-src\mysql-connector-c++-1.1.9\win
  - cmd: if %ARCH%==win32-msvc9 msbuild /P:Configuration=Release INSTALL.vcproj
  - cmd: if %ARCH%==win32-msvc10 call msbuild /P:Configuration=Release INSTALL.vcproj
  - cmd: if %ARCH%==x64-msvc10 call msbuild /P:Configuration=Release INSTALL.vcxproj
  - cmd: if %ARCH%==win32-msvc12 msbuild /P:Configuration=Release INSTALL.vcxproj
  - cmd: if %ARCH%==win32-msvc14 msbuild /P:Configuration=Release INSTALL.vcxproj
  - cmd: if %ARCH%==x64-msvc12 msbuild /P:Configuration=Release INSTALL.vcxproj
  - cmd: if %ARCH%==x64-msvc14 msbuild /P:Configuration=Release INSTALL.vcxproj
after_build:
  - cmd: cd "C:\projects\"
  - cmd: 7z a mysql-connectors-1.1.9_%ARCH%.zip %APPVEYOR_BUILD_FOLDER%/bin
  - cmd: 7z a mysql-connectors-1.1.9_%ARCH%.zip %APPVEYOR_BUILD_FOLDER%/include
  - cmd: 7z a mysql-connectors-1.1.9_%ARCH%.zip %APPVEYOR_BUILD_FOLDER%/lib
  - cmd: copy mysql-connectors-1.1.9_%ARCH%.zip C:\projects\mysql-connectors-ci\

on_finish:
  #RDP for finish
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

artifacts:
  - path: .\mysql-connectors-1.1.9_*.zip
 
